repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
        exclude: (mock_credentials|.+\/JjwtEngine.java|.+\/resources\/(organization-report-stream-public-key-local.pem|trusted-intermediary-private-key-local.pem))
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace

  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
      -   id: detect-secrets
          args: ['--baseline', '.secrets.baseline']
          exclude: (mock_credentials|.+\/JjwtEngine.java)

  - repo: local
    hooks:
      - id: code-format
        name: code-format
        entry: bash -c './gradlew spotlessCheck || (echo ""; echo "!!Automatically running spotlessApply!!"; ./gradlew spotlessApply && git add -u)'
        language: system
        types_or:
          - java
          - groovy
        pass_filenames: false
