openapi: 3.0.3
info:
  title: Trusted Intermediary Auth
  description: Provides authentication for the Trusted Intermediary service
  contact:
    email: cdc-ti@flexion.us
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Trusted Intermediary Repository
  url: https://github.com/CDCgov/trusted-intermediary
paths:
  /v1/auth:
    post:
      summary: Provides a short-lived token when a valid user signed JWT is provided
      requestBody:
        description: the user signed JWT
        required: true
        content:
          application/jwt:
            schema:
              type: string
      security:
        - OrgJwtAuth: [ ]
      responses:
        '200':
          description: the JWT is valid and an access token is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: failed to parse authorization request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedToParse'
        '401':
          description: Authentication failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedToParse'
components:
  schemas:
    AuthResponse:
      type: object
      properties:
        token_type:
          type: string
          description: bearer token
        access_token:
          type: string
          description: The token to use when authenticating against the service.
        scope:
          type: string
          description: client organization
    BadAuthentication:
      description: Bad authentication service configuration - Authentication failed
    FailedToParse:
      description: Authentication failed - could not parse request
    InternalFormatterError:
      description: Internal formatter exception occurred
  securitySchemes:
    OrgJwtAuth:
      type: apiKey
      in: header
      name: OUR-API-KEY
