openapi: 3.0.3
info:
  title: Trusted Intermediary ETOR
  description: A service that intermediates healthcare messages between a specific sender and receiver.
  contact:
    email: cdc-ti@flexion.us
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Trusted Intermediary Repository
  url: https://github.com/CDCgov/trusted-intermediary
paths:
  /v1/etor/demographics:
    post:
      summary: Forwards demographic information to a lab
      requestBody:
        description: A FHIR patient resource wrapped in a FHIR Bundle
        content:
          application/json:
            schema:
              $ref: 'https://github.com/LinuxForHealth/FHIR/blob/main/fhir-openapi/src/main/webapp/META-INF/openapi.json?raw=true#/components/schemas/Bundle'
        required: true
      security:
        - bearerAuthorization: [ ]
      responses:
        '200':
          description: The demographics were sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientDemographicsResponse'
        '400':
          description: Unable to parse demographics request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Authentication failed due to invalid token or unknown organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedRequestError'
  /v1/etor/orders:
    post:
      summary: Forwards orders to a lab
      requestBody:
        description: A FHIR order resource wrapped in a FHIR Bundle
        content:
          application/json:
            schema:
              $ref: 'https://github.com/LinuxForHealth/FHIR/blob/main/fhir-openapi/src/main/webapp/META-INF/openapi.json?raw=true#/components/schemas/Bundle'
        required: true
      security:
        - bearerAuthorization: [ ]
      responses:
        '200':
          description: The orders were sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdersResponse'
        '400':
          description: Unable to parse order request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Authentication failed due to invalid token or unknown organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedRequestError'
  /v1/etor/metadata/{id}:
    get:
      summary: Returns metadata about a specific submission
      parameters:
        - name: id
          in: path
          description: A valid id for the submission metadata
          required: true
          schema:
            type: string
      security:
        - bearerAuthorization: [ ]
      responses:
        '200':
          description: The metadata was returned successfully
          content:
            application/json:
            schema:
              $ref: '#/components/schemas/MetadataResponse'
        '401':
          description: Authentication failed due to invalid token or unknown organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedRequestError'
        '404':
          description: Unable to find requested metadata
          content:
            application/json:
            schema:
              $ref: '#/components/schemas/NotFoundError'
components:
  schemas:
    PatientDemographicsResponse:
      type: object
      properties:
        fhirResourceId:
          type: string
          example: Patient/infant-twin-1
        patientId:
          type: string
          example: MRN7465737865
    OrdersResponse:
      type: object
      properties:
        fhirResourceId:
          type: string
          example: Patient/infant-twin-1
        patientId:
          type: string
          example: MRN7465737865
    MetadataResponse:
      type: object
      properties:
        uniqueId:
          type: string
          example: abc123
        sender:
          type: string
          example: simulated-hospital
        receiver:
          type: string
          example: simulated-lab
        timeReceived:
          type: string
          example: 2023-12-01T12:00:00.000000Z
        hash:
          type: string
          example: abc123
    BadRequestError:
      description: Bad Request
      type: object
      properties:
        error:
          type: string
          example: Unable to parse request
    UnauthorizedRequestError:
      description: Unauthorized request
      type: object
      properties:
        error:
          type: string
          example: Authentication failed
    NotFoundError:
      description: Not Found
      type: object
      properties:
        error:
          type: string
          example: Unable to find requested data
  securitySchemes:
    bearerAuthorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
