name: Automated Staging Test - Submit Messages

on:
  schedule:
    - cron: "0 5 * * 2-6"  # Tuesday to Saturday at Midnight EST (5am UTC)
  workflow_dispatch:

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Call staging-test-submit.yml
        uses: ./.github/workflows/staging-test-submit-reusable.yml
        with:
          FILE_PATH: 'Automated/*.hl7'
