name: Automated Staging Test

on:
  schedule:
    - cron: "0 0 * * *"  # Midnight UTC every day
  workflow_dispatch:
  pull_request:

jobs:
  send_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.3.0/hurl_4.3.0_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.3.0_amd64.deb

      - name: Install jwt-cli
        run: |
            curl --silent --location https://github.com/mike-engel/jwt-cli/releases/latest/download/jwt-linux.tar.gz | tar xvz -C /usr/local/bin/
            sudo chmod +x /usr/local/bin/jwt
            jwt --version

      - name: Send HL7 sample messages to staging RS
        run: |
            host=https://staging.prime.cdc.gov:443
            client_id=flexion
            client_sender=automated-staging-test-sender
            jwt_token=$(jwt encode --exp='+5min' --jti $(uuidgen) --alg RS256 \
                -k $client_id.$client_sender -i $client_id.$client_sender \
                -s $client_id.$client_sender -a $host --no-iat -S "${{ secrets.TI_STAGING_PRIVATE_KEY }}")
            sample_path=$(pwd)/examples/Test/Staging
            for file in $sample_path/*.hl7; do
                hurl \
                    --variable fpath=$file \
                    --file-root $sample_path \
                    --variable url=$host \
                    --variable content-type=application/hl7-v2 \
                    --variable client-id=$client_id \
                    --variable client-sender=$client_sender \
                    --variable jwt=$jwt_token \
                    waters.hurl
            done
