name: Automated Staging Test - Run integration tests

on:
  schedule:
    - cron: "0 7 * * 2-6"  # Tuesday to Saturday at 2am EST (7am UTC) - two hours after `automated-staging-test-submit` runs
  workflow_dispatch:

jobs:
  test_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run automated tests
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AUTOMATED_TEST_AZURE_STORAGE_CONNECTION_STRING }}
          ORG_GRADLE_CONSOLE: plain
        run: ./gradlew rs-e2e:clean rs-e2e:automatedTest

      # - name: Send slack notification on test failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v2.0.0
      #   with:
      #     webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     webhook-type: incoming-webhook
      #     payload: |
      #       text: "Automated Staging RS Integration Test Failed!: https://github.com/CDCgov/trusted-intermediary/actions/runs/${{ github.run_id }}"
