name: Azure Load Tests

on:
  push:
    branches:
      - azure-load-tests
  #schedule:

    #- cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      rollbackCount:
        description: 'Number of migrations to rollback'
        required: true
        default: # of rollback you require in the file input


jobs:
  loadtest:
    name: Load Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Login to Azure using the CLI
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


        # Run the Azure Load Test
      - name: Run Load Test
        run: |
          az load test-run create \
            --resource-group "csels-rsti-internal-moderate-rg" \
            --load-test-name "jeff-load-test" \
            --test-run-name "github-action-triggered-test-run" \
            --test-id "9020b745-5fc4-4284-8803-04076ea09650" \
            --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
