name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:


jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Run unit tests
        run: ./gradlew clean app:test jacocoTestReport jacocoTestCoverageVerification


  e2e-tests:
    name: End-to-end Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Run e2e tests
        run: ./e2e-execute.sh


  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Code Formatting
        run: ./gradlew spotlessCheck

      - name: Sonar
        uses: sonarsource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=cdcgov
            -Dsonar.projectKey=trusted-intermediary
            -X

  securityScanAnalyze:
    name: CodeQL Security Scan
    uses: ./.github/workflows/codeql_reusable.yml

  terraform-ci:
    name: Terraform CI
    uses: ./.github/workflows/terraform-ci.yml
