name: CI/CD

on:
  push:
    branches:
      - main
      - terraform
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  terraform-deploy:
    name: 'Terraform Deploy'
    needs: ci
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: operations/app


    outputs:
      STAGING_REGISTRY: ${{ steps.export-terraform-output.outputs.STAGING_REGISTRY }}
      STAGING_APP: ${{ steps.export-terraform-output.outputs.STAGING_APP }}
      STAGING_ACR_USERNAME: ${{ steps.export-terraform-output.outputs.STAGING_ACR_USERNAME }}
      STAGING_ACR_PASSWORD: ${{ steps.export-terraform-output.outputs.STAGING_ACR_PASSWORD }}

    steps:

    - uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - id: export-terraform-output
      name: Export Terraform Output
      run: |
        echo "STAGING_REGISTRY=$(terraform output registry)"
        echo "::set-output name=STAGING_REGISTRY::$STAGING_REGISTRY"
        echo "STAGING_APP=$(terraform output publish_app)"
        echo "::set-output name=STAGING_APP::$STAGING_APP"
        echo "STAGING_ACR_USERNAME=$(terraform output acr_username)"
        echo "::add-mask::$STAGING_ACR_USERNAME"
        echo "::set-output name=STAGING_ACR_USERNAME::$STAGING_ACR_USERNAME"
        echo "STAGING_ACR_PASSWORD=$(terraform output acr_password)"
        echo "::add-mask::$STAGING_ACR_PASSWORD"
        echo "::set-output name=STAGING_ACR_PASSWORD::$STAGING_ACR_PASSWORD"

  staging-deploy:
    name: 'Staging Deploy'
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: staging
      REPO: trusted-intermediary-router
      APP: ${{ needs.jobs.terraform-deploy.outputs.STAGING_APP }}
      REGISTRY: ${{ needs.jobs.terraform-deploy.outputs.STAGING_REGISTRY }}
    secrets:
      ACR_USERNAME: ${{ needs.jobs.terraform-deploy.outputs.STAGING_ACR_USERNAME }}
      ACR_PASSWORD: ${{ needs.jobs.terraform-deploy.outputs.STAGING_ACR_PASSWORD }}
