name: CI/CD

on:
  push:
    branches:
      - main
      - terraform
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  terraform-deploy:
    name: 'Terraform Deploy'
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
    - name: Export Terraform Output
      run: |
        echo "STAGING_REGISTRY=$(terraform output registry)"
        echo "::set-output name=STAGING_REGISTRY::$STAGING_REGISTRY"
        echo "STAGING_APP=$(terraform output publish_app)"
        echo "::set-output name=STAGING_APP::$STAGING_APP"
        echo "STAGING_ACR_USERNAME=$(terraform output acr_username)"
        echo "::add-mask::$STAGING_ACR_USERNAME"
        echo "::set-output name=STAGING_ACR_USERNAME::$STAGING_ACR_USERNAME"
        echo "STAGING_ACR_PASSWORD=$(terraform output acr_password)"
        echo "::add-mask::$STAGING_ACR_PASSWORD"
        echo "::set-output name=STAGING_ACR_PASSWORD::$STAGING_ACR_PASSWORD"

  staging-deploy:
    name: 'Staging Deploy'
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: staging
      REPO: trusted-intermediary-router
      APP: ${{ jobs.terraform-deploy.outputs.STAGING_APP }}
      REGISTRY: ${{ jobs.terraform-deploy.outputs.STAGING_ACR_SERVER }}
    secrets:
      ACR_USERNAME: ${{ jobs.terraform-deploy.outputs.STAGING_ACR_USERNAME }}
      ACR_PASSWORD: ${{ jobs.terraform-deploy.outputs.STAGING_ACR_PASSWORD }}
      AZURE_CREDENTIALS: ${{ jobs.terraform-deploy.outputs.AZURE_CREDENTIALS }}
