name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  terraform-deploy:
    name: Staging Infrastructure Deploy
    needs: ci
    uses: ./.github/workflows/terraform-deploy_reusable.yml
    with:
      ENVIRONMENT: stg
      TERRAFORM_DIRECTORY: operations/environments/stg
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
      VPN_TLS_KEY: ${{ secrets.VPN_TLS_KEY }}
      VPN_CA_CERTIFICATE: ${{ secrets.VPN_CA_CERTIFICATE }}
      VPN_GITHUB_CERTIFICATE: ${{ secrets.VPN_GITHUB_CERTIFICATE}}
      VPN_GITHUB_SECRET_KEY: ${{ secrets.VPN_GITHUB_SECRET_KEY }}

  staging-deploy:
    name: Staging Application Deploy
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: stg
      REPO: trusted-intermediary-router
      REPO_DOCS: trusted-intermediary-docs
      APP: ${{ needs.terraform-deploy.outputs.APP }}
      REGISTRY: ${{ needs.terraform-deploy.outputs.REGISTRY }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
