name: ZAP

on:
  push:
    branches: [ story/77/dast/jorg3 ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: ZAP API Scan
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: ShadowJar
        run: ./gradlew shadowJar

      - name: run app in container
        run: docker compose up --build -d

      - name: Run e2e
        run: ./gradlew :e2e:test --info

      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly

      - name: Create docker network
        run: docker network create zapnet

      - name: Run ZAP API Scan
        run: |
          sudo docker run --net zapnet -v $(pwd):/zap/wrk/:rw --user root -t owasp/zap2docker-weekly zap-api-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8080 -f openapi

#          docker run -u zap -p 8081:8081 -i owasp/zap2docker-weekly zap.sh -daemon -host 0.0.0.0 -port 8081 -config api.addrs.addr.name=/v1/etor/order -config api.addrs.addr.regex=true -config api.disablekey=true -addoninstall openapi

      - name: "Upload Report"
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: /zap/wrk/api-scan-report.html
