name: ZAP

on:
  push:
    branches: [ story/77/dast/jorg3 ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: ZAP API Scan
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: ShadowJar
        run: ./gradlew shadowJar
      - name: run app in container
        run: docker compose up --build -d

      - name: Run e2e
        run: ./gradlew :e2e:test

      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly
      - name: Run ZAP API Scan
        run: |
          docker run -u zap -p 8080:8080 -i owasp/zap2docker-weekly zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=/v1/etor/order -config api.addrs.addr.regex=true -config api.disablekey=true -addoninstall openapi
#          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t http://localhost:8080/v1/etor/order -f openapi
#      - name: "Upload Report"
#        uses: actions/upload-artifact@v1
#        with:
#          name: zap-scan-report
#          path: ./script/report.html
