name: ZAP

on:
  push:
    branches: [ story/77/dast/jorg3 ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: ZAP API Scan
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: ShadowJar
        run: ./gradlew shadowJar
      - name: run app in container
        run: docker compose up --build -d
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log current directory
        run: echo ${pwd}
      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly
      - name: Run ZAP API Scan
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t http://localhost:8080/v1/etor/order zap-api-scan.py -t openapi.json -f openapi -c api-scan.conf
#      - name: "Upload Report"
#        uses: actions/upload-artifact@v1
#        with:
#          name: zap-scan-report
#          path: ./script/report.html
