name: 'Container Build & Deploy'

on:
  workflow-call:
    inputs:
      REGISTRY:
        required: true
        type: string
      REPO:
        required: true
        type: string
      APP:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      PUBLISH_PROFILE:
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Build JAR
      run: ./gradlew clean :app:shadowJar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: 'https://${{ env.REGISTRY }}/'
        username: '${{ secrets.ACR_USERNAME }}'
        password: '${{ secrets.ACR_PASSWORD }}'

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}'
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ env.ENVIRONMENT }}
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.APP }}'
        slot-name: 'production'
        publish-profile: '${{ secrets.PUBLISH_PROFILE }}'
        images: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}'