name: 'Container Build & Deploy'

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Nothing'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo 'Nothing'
