name: 'Container Build & Deploy'

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      REPO:
        required: true
        type: string
      APP:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      PUBLISH_PROFILE:
        required: true

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto
        cache: gradle

    - name: Build JAR
      run: ./gradlew clean :app:shadowJar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Testing env
      run: |
        pwd
        ls -la ./app/build/libs/
        ls -la ./app/build/libs/app-all.jar
      shell: bash

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: 'https://${{ inputs.REGISTRY }}/'
        username: '${{ secrets.ACR_USERNAME }}'
        password: '${{ secrets.ACR_PASSWORD }}'

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: '${{ inputs.REGISTRY }}/${{ inputs.REPO }}:${{ github.sha }}'
        file: ./Dockerfile
        context: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: '${{ inputs.ENVIRONMENT }}'
      url: '${{ steps.deploy-to-webapp.outputs.webapp-url }}'
  
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ inputs.APP }}'
        slot-name: 'production'
        publish-profile: '${{ secrets.PUBLISH_PROFILE }}'
        images: '${{ inputs.REGISTRY }}/${{ inputs.REPO }}:${{ github.sha }}'