name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:

  terraform-deploy:
    name: Dev Infrastructure Deploy
    uses: ./.github/workflows/terraform-deploy_reusable.yml
    with:
      TERRAFORM_DIRECTORY: operations/environments/dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  dev-deploy:
    name: Dev Application Deploy
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: dev
      REPO: trusted-intermediary-router
      REPO_DOCS: trusted-intermediary-docs
      APP: ${{ needs.terraform-deploy.outputs.APP }}
      REGISTRY: ${{ needs.terraform-deploy.outputs.REGISTRY }}
    secrets:
      ACR_USERNAME: ${{ needs.terraform-deploy.outputs.ACR_USERNAME }}
      ACR_PASSWORD: ${{ needs.terraform-deploy.outputs.ACR_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
