name: METRICS

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: DORA Metrics
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Setup DORA metrics application
        run: ./dora-metrics-setup.sh

      - name: Run DORA metrics application
        env:
          GITHUB_USERNAME: JohnNKing
          GITHUB_PASSWORD: ${{ secrets.DORA_METRICS_ACCESS_TOKEN_JOHNNKING }}
        working-directory: devops-deployment-metrics
        run: poetry run devops-deployment-metrics -c config.toml

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: deployments
          path: devops-deployment-metrics/deployments.csv
