name: METRICS

on:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: DORA Metrics
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: gradle

      - name: Run DORA Requirements
        env:
          GITHUB_USER: JohnNKing
          GITHUB_TOKEN: ${{ secrets.DORA_METRICS_ACCESS_TOKEN_JOHNNKING }}
        run: ./dora-requirements.sh

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dora-metrics
          path: dora-metrics.csv
