name: Fortify

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 1,15 * *'
  workflow_dispatch:


jobs:
  trusted-intermediary:
    uses: ./.github/workflows/scan-template.yml
    with:
      repository: CDCgov/trusted-intermediary
      branch: main
      workDir: ./
      appName: trusted-intermediary
      appVersionId: 12016
    secrets: inherit # pragma: allowlist secret
