name: Golden Copy Staging Test - Run integration tests

on:
  schedule:
    - cron: "0 7 * * 2-6"  # Tuesday to Saturday at 2am EST (7am UTC) - two hours after `automated-staging-test-submit` runs
  workflow_dispatch:

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Call staging-test-run.yml
        uses: ./.github/workflows/staging-test-run-reusable.yml
        with:
          FILE_PATH: '../examples/Test/GoldenCopy/Expected/'
          NAME: 'Golden Copy'
          TEST_TYPE: 'goldenCopyTest'
