name: Production Deploy

on:
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  terraform-deploy:
    name: Prod Infrastructure Deploy
    needs: ci
    uses: ./.github/workflows/terraform-deploy_reusable.yml
    with:
      ENVIRONMENT: prd
      TERRAFORM_DIRECTORY: operations/environments/prd
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
      VPN_TLS_KEY: ${{ secrets.VPN_TLS_KEY }}
      VPN_CA_CERTIFICATE: ${{ secrets.VPN_CA_CERTIFICATE }}
      VPN_GITHUB_CERTIFICATE: ${{ secrets.VPN_GITHUB_CERTIFICATE}}
      VPN_GITHUB_SECRET_KEY: ${{ secrets.VPN_GITHUB_SECRET_KEY }}
      TERRAFORM_APPLY_PARAMETERS: -var="alert_slack_email=${{ secrets.ALERT_SLACK_EMAIL }}"

  prod-deploy:
    name: Prod Application Deploy
    needs: terraform-deploy
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      ENVIRONMENT: prd
      REPO: trusted-intermediary-router
      APP: ${{ needs.terraform-deploy.outputs.APP }}
      REGISTRY: ${{ needs.terraform-deploy.outputs.REGISTRY }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_CDC_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDC_DMZ_C1_SUBSCRIPTION_ID }}
