name: 'Terraform CI'

on:
  workflow_call:

jobs:
  terraform-ci:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: operations/app

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
